select * from HR;

--OVERALL ATTRITION HAPPENED IN  THE COMPANY
select count(CASE WHEN ATTRITION= '1' THEN 1 END) AS ATTRITIONCOUNT,
       COUNT(*) AS TOTAL_EMPLOYEES
 FROM HR;

 --PRESENCE OF OERTIME AND CORRELATION IN ATTRITION
SELECT OVERTIME, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR 
WHERE ATTRITION=1
GROUP BY OVERTIME

--GENDER DISTRIBUTION IN THE COMPANY
SELECT GENDER , COUNT (*)AS TOTAL_EMPLOYEES, COUNT (*) FROM HR
WHERE ATTRITION = 1
GROUP BY GENDER;

SELECT GENDER , COUNT (*)FROM HR
WHERE ATTRITION= 1
GROUP BY GENDER;

SELECT GENDER,
       COUNT(CASE WHEN GENDER = 'MALE' THEN 1 END),
	   COUNT(CASE WHEN GENDER = 'FEMALE' THEN 1 END),
	   COUNT(*) AS TOTAL_EMPLOYEES
	   FROM HR
	   WHERE ATTRITION= 1
	   GROUP BY GENDER;

--THERE IS A NEGATIVE CORRELATION AMONGST PERFORMANCE RATING AND ATTRITION
select performancerating 
from HR
where attrition =1;

SELECT PERFORMANCERATING, COUNT(CASE WHEN ATTRITION = 1 THEN 1 END)AS ATTRITION_COUNT
FROM HR
GROUP BY PERFORMANCERATING;

--ATTRITION COUNT BASED ON THE JOB ROLES
SELECT DEPARTMENT, JOBROLE, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY JOBROLE , DEPARTMENT
ORDER BY ATTRITION_COUNT DESC;

--ATTRITION COUNT BASED ON DISTANCE FROM HOME VARIABLE
SELECT DISTANCEFROMHOME, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY DISTANCEFROMHOME
ORDER BY ATTRITION_COUNT DESC;

SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY DEPARTMENT

--RELATION O SALARY AND ATTRITION--NEGATIVE CORRELATION AMONGST SALARY HIKES
SELECT PERCENTSALARYHIKE, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION= 1
GROUP BY PERCENTSALARYHIKE 
ORDER BY ATTRITION_COUNT DESC;

--EDUCATION FIELD IS RELATED TO ATTRITION COUNT OR NOT
SELECT EDUCATIONFIELD, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION= 1
GROUP BY EDUCATIONFIELD
ORDER BY ATTRITION_COUNT DESC;

--RELATION BETWEEN YEARS IN CURRENT ROLE AND ATTRITION COUNT
SELECT YEARSINCURRENTROLE, COUNT (CASE WHEN ATTRITION= 1 THEN 1 ELSE 0 END)AS ATTRITION_COUNT FROM HR
WHERE YEARSINCURRENTROLE >(SELECT AVG(YEARSINCURRENTROLE) FROM HR)
GROUP BY YEARSINCURRENTROLE
ORDER BY ATTRITION_COUNT DESC;
 
 --EMPLOYEES WHO ARE WORKING IN THE COMPANY FROM LAST 5-10 YEARS HAVE YHE HIGHEST ATTRITION_COUNT
 --JOB SATISFACTION AND MONTHLY INCOME
 SELECT JOBSATISFACTION, COUNT(*)AS ATTRITION_COUNT
 FROM HR
 WHERE ATTRITION =1 AND MONTHLYINCOME < (SELECT AVG(MONTHLYINCOME) FROM HR)
 GROUP BY JOBSATISFACTION;
 --MONTHLY INCOME PLAYS A VITAL ROLE IN ATTRITION COUNT IRRESPECTIVE THE SATISFACTION FROM THE OB IS ON THE HIGHEST SIDE
 --EMPLOYEE ATTRITION  BASED ON THE AGE RANGE
 SELECT CASE WHEN AGE<= 29 THEN '18-29'
                                  WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
								  WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
								  WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
								  ELSE '60 OR OLDER'
								  END AS 'AGE RANGE', COUNT(*) AS 'NUMBER OF ATTRITION BASED ON AGE RANGE'
FROM HR
WHERE ATTRITION =1 AND YEARSATCOMPANY >=1
GROUP BY CASE WHEN AGE<= 29 THEN '18-29'
                                  WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
								  WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
								  WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
								  ELSE '60 OR OLDER'
								  END ;

SELECT MAX(DAILYRATE)  FROM HR
WHERE ATTRITION =1;

SELECT MIN(DAILYRATE)  FROM HR
WHERE ATTRITION =1;


SELECT MAX(MONTHLYRATE)  FROM HR
WHERE ATTRITION =1;

SELECT MIN(MONTHLYRATE)  FROM HR
WHERE ATTRITION =1;


SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE ATTRITION =1 AND DAILYRATE < (SELECT AVG(DAILYRATE) FROM HR) AND MONTHLYRATE < (SELECT AVG(MONTHLYRATE) FROM HR) AND MONTHLYINCOME < (SELECT AVG(MONTHLYINCOME) FROM HR);

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND DailyRate < (SELECT AVG(DAILYRATE) FROM HR)-- AND MonthlyRate < (SELECT AVG(MONTHLYRATE) FROM HR) AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR);;

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND MonthlyRate < (SELECT AVG(MONTHLYRATE) FROM HR) 

SELECT COUNT(*) AS 'ATTRITION_COUNT'
FROM HR
WHERE Attrition = 1 AND MonthlyIncome < (SELECT AVG(MONTHLYINCOME) FROM HR);

SELECT * FROM HR;

SELECT ENVIRONMENTSATISFACTION, RELATIONSHIPSATISFACTION, COUNT (*) AS 'ATTRITION_COUNT'
FROM HR 
WHERE ATTRITION =1
GROUP BY ENVIRONMENTSATISFACTION, RELATIONSHIPSATISFACTION
ORDER BY 'ATTRITION_COUNT' DESC;

SELECT MARITALSTATUS, COUNT (*) AS 'ATTRITION_COUNT'
FROM HR
WHERE ATTRITION =1
GROUP BY MARITALSTATUS;